### ISSUE TITLE
LyndaDecryptor has stopped working

### ISSUE THREAD

**Issue by emon2196** [h4ck-rOOt/Lynda-Decryptor#17]
> C:\Users\TanDat\Downloads\Lynda_v1.2>LyndaDecryptor /D "C:\Users\TanDat\AppData\
Local\lynda.com\Lynda.com Desktop App\offline\ldc_dl_courses\122474" /DB "C:\Use
rs\TanDat\AppData\Local\lynda.com\Lynda.com Desktop App\db.sqlite" /OUT "E:\Lynd
a"
[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

> [DB] Creating db connection...
[DB] DB successfully connected and opened!

> Press any key to exit the program...

> Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   at LyndaDecryptor.Program.<DecryptAll>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Ob
ject state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object sta
te)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

I follow the steps but got errors "LyndaDecryptor has stopped working". I'm using win 8.1 home and run cmd with admin. 
Plz help !

**Comment by emon2196** [comment]
I fixed it by follow #4. Many thanks <3

**Comment by Dev-iL** [comment]
@emon2196 then close the issue please, seeing how it is a duplicate...

**Comment by emon2196** [comment]
close #17
