### ISSUE TITLE
Error -the programm looks for video2brain folder instead of lynda.com folder

### ISSUE THREAD

**Issue by MaxBass** [h4ck-rOOt/Lynda-Decryptor#18]
Hi!
I've downloaded the Lynda.com desktop app (windows 7) and tried to see if I can decrypt the files.
The problem is that the decryptor is looking for the video2brain app and not Lynda.com app as can be seen in the error below.
Did I do something wrong? (at the lynda.com directory I have Lynda.com desktop app and not video2brain desktop app, as the error pointed  out)

E:\Downloads\Lynda_v1.2>LyndaDecryptor /D "D:\Lynda\ldc_dl_courses\148580" /DB "
C:\Users\USERNAME\AppData\Local\lynda.com\Lynda.com Desktop App\db.sqlite" /OUT
"D:\Lynda\out"
[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

[DB] Creating db connection...
[START] **Error occured: Could not find a part of the path 'C:\Users\MaxBass\AppDa
ta\Local\lynda.com\video2brain Desktop App'.**

Usage (Directory):   LyndaDecryptor /D PATH_TO_FOLDER [OPTIONS]
Usage (File): LyndaDecryptor /F ENCRYPTED_FILE   DECRYPTED_FILE [OPTIONS]

Flags:
        /D      Source files are located in a folder.
        /F      Source and Destination file are specified.
        /DB     Search for Database or specify the location on your system.
        /RM     Removes all files after decryption is complete.
        /OUT    Specifies an output directory instead of using default directory
.

Press any key to exit the program...

**Comment by MaxBass** [comment]
I've tried to copy the Lynda.com Desktop app and renamed it into "video2brain Desktop app", it passed that phase but threw another error. What am I missing?

E:\Downloads\Lynda_v1.2>LyndaDecryptor /D "D:\Lynda\ldc_dl_courses\148580" /DB "
C:\Users\USERNAME\AppData\Local\lynda.com\Lynda.com Desktop App\db.sqlite" /OUT
"D:\Lynda\out"
[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

[DB] Creating db connection...
[DB] DB successfully connected and opened!


Press any key to exit the program...

Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   at LyndaDecryptor.Program.<DecryptAll>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__1(Ob
ject state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object sta
te)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

E:\Downloads\Lynda_v1.2>
