### ISSUE TITLE
Unhandled Exception: System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by kahanit** [h4ck-rOOt/Lynda-Decryptor#4]
You have done an awesome work on this project!

All the other courses converted just fine. But when I tried to convert below courses below exception was thrown.

**Courses**
https://www.lynda.com/Web-Interaction-Design-tutorials/JavaScript-Templating/156166-2.html
https://www.lynda.com/Selenium-tutorials/Mastering-Selenium-Testing-Tools/521207-2.html

**Exception**
Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   at LyndaDecryptor.Program.<DecryptAll>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by fransyeng** [comment]
Thank you for all that you have done. But I'm sorry that I'm a newbie and
don't know how to use this program. But I neet it to convert my lynda
offline video course. So would you please to teach or lead me how to
convert *.lynda video by this program.

2016-09-16 16:18 GMT+07:00 Amit Sidhpura <notifications@github.com>:

**Comment by MuhamadHakimi** [comment]
Having the same problem but you can still decrypt the video by renaming the course number folder in the offline folder to 7 digit instead of 6. i.e 156166->1561666.

But the output video will be in that folder although you specificy it in command.

And the naming and foldering also will be mess up as the course number doesnt exist in db.sqlite

**Comment by aadimator** [comment]
Having the same problem. Any solution?

**Comment by Dev-iL** [comment]
Guys this is a duplicate of #3. 

As a temporary workaround, you need to edit the sqlite database containing course data (e.g. `C:\Users\<USER>\AppData\Local\lynda.com\Lynda.com Desktop App\db.sqlite`), open the table `Video` and make sure there are no `(null)` entries there. You can find the exact course name in the `Course` table under the `Title` field having the same `ID` as the `CourseId` in the `Video` table. Once you do that - the converter will work.

I suppose one can write some SQL query that fills these fields automatically, but unfortunately I don't know how to do that.

**Comment by ktsarlz** [comment]
Why is that when I convert by folder, it always stops in after converting 4 videos? Am I doing it wrong?

**Comment by thetriplet3** [comment]
@Dev-iL 
I kinda change the query to correct the issue. Please check the attached file for the fix.
[Query.txt](https://github.com/h4ck-rOOt/Lynda-Decryptor/files/545228/Query.txt)

**Comment by ktsarlz** [comment]
@thetriplet3 How do I do that? Do I have to recompile the project?

**Comment by thetriplet3** [comment]
@ktsarlz Yup! replace the query, recompile and run!

**Comment by ktsarlz** [comment]
@thetriplet3 I can't compile the source file. Mainly because I only have VS 2008. It gives an error about 14.0 etc :(

**Comment by thetriplet3** [comment]
@ktsarlz [Here ](https://goo.gl/mnSYO4)is the compiled exe file. Tell me if you get any issues.

**Comment by ktsarlz** [comment]
@thetriplet3 Wow! Thanks for that. I tried running it now, But I when the process goes on it still stops at after 4 videos :/

**Comment by tao101** [comment]
guys anyone can help me i get this error when i run it 
[STATUS] Couldn't find db entry for file: E:\lynda\ldc_dl_courses\1014613\114513_83218ac34c1834c26781fe4bde918ee4.lynda
[STATUS] Using the default behaviour!
